import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/layouts/Navbar/Navbar";
import AuthProvider from "./providers/AuthProvider";
import AnimatedBackground from "@/components/layouts/AnimatedBackground";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "사과게임",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* 2. 배경 컴포넌트를 여기에 렌더링합니다. */}
          <AnimatedBackground />

          {/* 3. 모든 페이지 콘텐츠를 z-10을 가진 컨테이너로 감싸서 배경 위에 오도록 합니다. */}
          <div className="relative z-10 flex min-h-screen flex-col">
            <Navbar />
            {/* 페이지 콘텐츠가 이 main 태그 안에 렌더링됩니다. */}
            <main className="flex-grow">{children}</main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
